// Mocks generated by Mockito 5.4.6 from annotations
// in pokemon_explorer/test/features/pokemon/presentation/pokemon_list_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pokemon_explorer/core/error/failures.dart' as _i6;
import 'package:pokemon_explorer/core/network/network_info.dart' as _i10;
import 'package:pokemon_explorer/core/usecases/usecase.dart' as _i9;
import 'package:pokemon_explorer/features/pokemon/domain/entities/pokemon.dart'
    as _i7;
import 'package:pokemon_explorer/features/pokemon/domain/repositories/pokemon_repository.dart'
    as _i2;
import 'package:pokemon_explorer/features/pokemon/domain/usecases/get_pokemon_list_use_case.dart'
    as _i4;
import 'package:pokemon_explorer/features/pokemon/domain/usecases/refresh_pokemon_list_use_case.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonRepository_0 extends _i1.SmartFake
    implements _i2.PokemonRepository {
  _FakePokemonRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetPokemonListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonListUseCase extends _i1.Mock
    implements _i4.GetPokemonListUseCase {
  MockGetPokemonListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokemonRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PokemonRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Pokemon>>> call(
    _i4.PokemonListParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i7.Pokemon>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.Pokemon>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Pokemon>>>);
}

/// A class which mocks [RefreshPokemonListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshPokemonListUseCase extends _i1.Mock
    implements _i8.RefreshPokemonListUseCase {
  MockRefreshPokemonListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PokemonRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokemonRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.PokemonRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>> call(_i9.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i6.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i3.Unit>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i10.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i5.Stream<bool>.empty(),
          )
          as _i5.Stream<bool>);
}
