// Mocks generated by Mockito 5.4.6 from annotations
// in pokemon_explorer/test/features/pokemon/data/repositories/pokemon_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:pokemon_explorer/core/network/network_info.dart' as _i7;
import 'package:pokemon_explorer/core/services/image_optimization_service.dart'
    as _i8;
import 'package:pokemon_explorer/features/pokemon/data/datasources/pokemon_local_datasource.dart'
    as _i6;
import 'package:pokemon_explorer/features/pokemon/data/datasources/pokemon_remote_datasource.dart'
    as _i3;
import 'package:pokemon_explorer/features/pokemon/data/models/pokemon_detail_model.dart'
    as _i2;
import 'package:pokemon_explorer/features/pokemon/data/models/pokemon_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetailModel_0 extends _i1.SmartFake
    implements _i2.PokemonDetailModel {
  _FakePokemonDetailModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokemonRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteDataSource extends _i1.Mock
    implements _i3.PokemonRemoteDataSource {
  MockPokemonRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PokemonModel>> getPokemonList(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonList, [offset, limit]),
            returnValue: _i4.Future<List<_i5.PokemonModel>>.value(
              <_i5.PokemonModel>[],
            ),
          )
          as _i4.Future<List<_i5.PokemonModel>>);

  @override
  _i4.Future<_i2.PokemonDetailModel> getPokemonDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonDetail, [id]),
            returnValue: _i4.Future<_i2.PokemonDetailModel>.value(
              _FakePokemonDetailModel_0(
                this,
                Invocation.method(#getPokemonDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.PokemonDetailModel>);
}

/// A class which mocks [PokemonLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonLocalDataSource extends _i1.Mock
    implements _i6.PokemonLocalDataSource {
  MockPokemonLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.PokemonModel>> getCachedPokemonList(
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPokemonList, [offset, limit]),
            returnValue: _i4.Future<List<_i5.PokemonModel>>.value(
              <_i5.PokemonModel>[],
            ),
          )
          as _i4.Future<List<_i5.PokemonModel>>);

  @override
  _i4.Future<void> cachePokemonList(List<_i5.PokemonModel>? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#cachePokemonList, [pokemon]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.PokemonDetailModel> getCachedPokemonDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPokemonDetail, [id]),
            returnValue: _i4.Future<_i2.PokemonDetailModel>.value(
              _FakePokemonDetailModel_0(
                this,
                Invocation.method(#getCachedPokemonDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.PokemonDetailModel>);

  @override
  _i4.Future<void> cachePokemonDetail(_i2.PokemonDetailModel? detail) =>
      (super.noSuchMethod(
            Invocation.method(#cachePokemonDetail, [detail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isListCacheValid() =>
      (super.noSuchMethod(
            Invocation.method(#isListCacheValid, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> isCacheValid(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isCacheValid, [id]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePokemonImagePaths(int? id, String? listPath) =>
      (super.noSuchMethod(
            Invocation.method(#updatePokemonImagePaths, [id, listPath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePokemonDetail(_i2.PokemonDetailModel? detail) =>
      (super.noSuchMethod(
            Invocation.method(#updatePokemonDetail, [detail]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);
}

/// A class which mocks [ImageOptimizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageOptimizationService extends _i1.Mock
    implements _i8.ImageOptimizationService {
  MockImageOptimizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> optimizeAndCacheImage({
    required String? imageUrl,
    required String? savePath,
    required int? targetWidth,
    required int? targetHeight,
    int? quality = 85,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#optimizeAndCacheImage, [], {
              #imageUrl: imageUrl,
              #savePath: savePath,
              #targetWidth: targetWidth,
              #targetHeight: targetHeight,
              #quality: quality,
            }),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#optimizeAndCacheImage, [], {
                  #imageUrl: imageUrl,
                  #savePath: savePath,
                  #targetWidth: targetWidth,
                  #targetHeight: targetHeight,
                  #quality: quality,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}
