// Mocks generated by Mockito 5.4.6 from annotations
// in pokemon_explorer/test/mocks/mock_config.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i18;
import 'package:pokemon_explorer/core/error/failures.dart' as _i9;
import 'package:pokemon_explorer/core/network/network_info.dart' as _i16;
import 'package:pokemon_explorer/core/services/image_optimization_service.dart'
    as _i17;
import 'package:pokemon_explorer/core/usecases/usecase.dart' as _i15;
import 'package:pokemon_explorer/features/pokemon/data/datasources/pokemon_local_datasource.dart'
    as _i8;
import 'package:pokemon_explorer/features/pokemon/data/datasources/pokemon_remote_datasource.dart'
    as _i5;
import 'package:pokemon_explorer/features/pokemon/data/models/pokemon_detail_model.dart'
    as _i2;
import 'package:pokemon_explorer/features/pokemon/data/models/pokemon_model.dart'
    as _i7;
import 'package:pokemon_explorer/features/pokemon/domain/entities/pokemon.dart'
    as _i10;
import 'package:pokemon_explorer/features/pokemon/domain/entities/pokemon_detail.dart'
    as _i11;
import 'package:pokemon_explorer/features/pokemon/domain/repositories/pokemon_repository.dart'
    as _i4;
import 'package:pokemon_explorer/features/pokemon/domain/usecases/get_pokemon_detail_use_case.dart'
    as _i13;
import 'package:pokemon_explorer/features/pokemon/domain/usecases/get_pokemon_list_use_case.dart'
    as _i12;
import 'package:pokemon_explorer/features/pokemon/domain/usecases/refresh_pokemon_list_use_case.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePokemonDetailModel_0 extends _i1.SmartFake
    implements _i2.PokemonDetailModel {
  _FakePokemonDetailModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePokemonRepository_2 extends _i1.SmartFake
    implements _i4.PokemonRepository {
  _FakePokemonRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PokemonRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRemoteDataSource extends _i1.Mock
    implements _i5.PokemonRemoteDataSource {
  MockPokemonRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.PokemonModel>> getPokemonList(int? offset, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonList, [offset, limit]),
            returnValue: _i6.Future<List<_i7.PokemonModel>>.value(
              <_i7.PokemonModel>[],
            ),
          )
          as _i6.Future<List<_i7.PokemonModel>>);

  @override
  _i6.Future<_i2.PokemonDetailModel> getPokemonDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonDetail, [id]),
            returnValue: _i6.Future<_i2.PokemonDetailModel>.value(
              _FakePokemonDetailModel_0(
                this,
                Invocation.method(#getPokemonDetail, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.PokemonDetailModel>);
}

/// A class which mocks [PokemonLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonLocalDataSource extends _i1.Mock
    implements _i8.PokemonLocalDataSource {
  MockPokemonLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.PokemonModel>> getCachedPokemonList(
    int? offset,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPokemonList, [offset, limit]),
            returnValue: _i6.Future<List<_i7.PokemonModel>>.value(
              <_i7.PokemonModel>[],
            ),
          )
          as _i6.Future<List<_i7.PokemonModel>>);

  @override
  _i6.Future<void> cachePokemonList(List<_i7.PokemonModel>? pokemon) =>
      (super.noSuchMethod(
            Invocation.method(#cachePokemonList, [pokemon]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.PokemonDetailModel> getCachedPokemonDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedPokemonDetail, [id]),
            returnValue: _i6.Future<_i2.PokemonDetailModel>.value(
              _FakePokemonDetailModel_0(
                this,
                Invocation.method(#getCachedPokemonDetail, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.PokemonDetailModel>);

  @override
  _i6.Future<void> cachePokemonDetail(_i2.PokemonDetailModel? detail) =>
      (super.noSuchMethod(
            Invocation.method(#cachePokemonDetail, [detail]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isListCacheValid() =>
      (super.noSuchMethod(
            Invocation.method(#isListCacheValid, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> isCacheValid(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isCacheValid, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> clearCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePokemonImagePaths(int? id, String? listPath) =>
      (super.noSuchMethod(
            Invocation.method(#updatePokemonImagePaths, [id, listPath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePokemonDetail(_i2.PokemonDetailModel? detail) =>
      (super.noSuchMethod(
            Invocation.method(#updatePokemonDetail, [detail]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [PokemonRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPokemonRepository extends _i1.Mock implements _i4.PokemonRepository {
  MockPokemonRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i9.Failure, List<_i10.Pokemon>>> getPokemonList({
    required int? offset,
    required int? limit,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonList, [], {
              #offset: offset,
              #limit: limit,
              #forceRefresh: forceRefresh,
            }),
            returnValue:
                _i6.Future<_i3.Either<_i9.Failure, List<_i10.Pokemon>>>.value(
                  _FakeEither_1<_i9.Failure, List<_i10.Pokemon>>(
                    this,
                    Invocation.method(#getPokemonList, [], {
                      #offset: offset,
                      #limit: limit,
                      #forceRefresh: forceRefresh,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, List<_i10.Pokemon>>>);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i11.PokemonDetail>> getPokemonDetail({
    required int? id,
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPokemonDetail, [], {
              #id: id,
              #forceRefresh: forceRefresh,
            }),
            returnValue:
                _i6.Future<_i3.Either<_i9.Failure, _i11.PokemonDetail>>.value(
                  _FakeEither_1<_i9.Failure, _i11.PokemonDetail>(
                    this,
                    Invocation.method(#getPokemonDetail, [], {
                      #id: id,
                      #forceRefresh: forceRefresh,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i11.PokemonDetail>>);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i3.Unit>> refreshPokemonList() =>
      (super.noSuchMethod(
            Invocation.method(#refreshPokemonList, []),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i9.Failure, _i3.Unit>(
                this,
                Invocation.method(#refreshPokemonList, []),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i3.Unit>>);
}

/// A class which mocks [GetPokemonListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonListUseCase extends _i1.Mock
    implements _i12.GetPokemonListUseCase {
  MockGetPokemonListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PokemonRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokemonRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.PokemonRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, List<_i10.Pokemon>>> call(
    _i12.PokemonListParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i3.Either<_i9.Failure, List<_i10.Pokemon>>>.value(
                  _FakeEither_1<_i9.Failure, List<_i10.Pokemon>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, List<_i10.Pokemon>>>);
}

/// A class which mocks [GetPokemonDetailUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPokemonDetailUseCase extends _i1.Mock
    implements _i13.GetPokemonDetailUseCase {
  MockGetPokemonDetailUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PokemonRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokemonRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.PokemonRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i11.PokemonDetail>> call(
    _i13.PokemonDetailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i6.Future<_i3.Either<_i9.Failure, _i11.PokemonDetail>>.value(
                  _FakeEither_1<_i9.Failure, _i11.PokemonDetail>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i11.PokemonDetail>>);
}

/// A class which mocks [RefreshPokemonListUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockRefreshPokemonListUseCase extends _i1.Mock
    implements _i14.RefreshPokemonListUseCase {
  MockRefreshPokemonListUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.PokemonRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakePokemonRepository_2(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i4.PokemonRepository);

  @override
  _i6.Future<_i3.Either<_i9.Failure, _i3.Unit>> call(_i15.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i6.Future<_i3.Either<_i9.Failure, _i3.Unit>>.value(
              _FakeEither_1<_i9.Failure, _i3.Unit>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i6.Future<_i3.Either<_i9.Failure, _i3.Unit>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i16.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i6.Stream<bool>.empty(),
          )
          as _i6.Stream<bool>);
}

/// A class which mocks [ImageOptimizationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageOptimizationService extends _i1.Mock
    implements _i17.ImageOptimizationService {
  MockImageOptimizationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> optimizeAndCacheImage({
    required String? imageUrl,
    required String? savePath,
    required int? targetWidth,
    required int? targetHeight,
    int? quality = 85,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#optimizeAndCacheImage, [], {
              #imageUrl: imageUrl,
              #savePath: savePath,
              #targetWidth: targetWidth,
              #targetHeight: targetHeight,
              #quality: quality,
            }),
            returnValue: _i6.Future<String>.value(
              _i18.dummyValue<String>(
                this,
                Invocation.method(#optimizeAndCacheImage, [], {
                  #imageUrl: imageUrl,
                  #savePath: savePath,
                  #targetWidth: targetWidth,
                  #targetHeight: targetHeight,
                  #quality: quality,
                }),
              ),
            ),
          )
          as _i6.Future<String>);
}
